const express = require('express');
const router = express.Router();
const multer = require('multer');
const courseController = require('../controllers/courseController');
const auth = require('../middleware/auth');

// Multer for certificate PDF upload (memory storage; controller expects req.file.buffer)
const certificatePdfFilter = (req, file, cb) => {
  if (file.mimetype === 'application/pdf') {
    cb(null, true);
  } else {
    cb(new Error('Invalid file type. Only PDF files are allowed.'), false);
  }
};
const uploadCertificatePdf = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024 }, // 5MB
  fileFilter: certificatePdfFilter
}).single('certificate');

// 4-arg error handler: catch multer and other errors for certificate upload, return 400 JSON
const certificateUploadErrorHandler = (err, req, res, next) => {
  if (res.headersSent) return next(err);
  if (err instanceof multer.MulterError) {
    if (err.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({ success: false, message: 'Certificate file is too large. Maximum size is 5MB.' });
    }
    if (err.code === 'LIMIT_UNEXPECTED_FILE') {
      return res.status(400).json({ success: false, message: 'Unexpected field. Use field name: certificate.' });
    }
    return res.status(400).json({ success: false, message: err.message || 'File upload error.' });
  }
  if (err.message && err.message.includes('Invalid file type')) {
    return res.status(400).json({ success: false, message: err.message });
  }
  return res.status(400).json({ success: false, message: err.message || 'Certificate upload failed.' });
};

// Multer for certificate template PDF (creator uploads per course; generated PDFs can be larger due to embedded images)
const TEMPLATE_PDF_MAX_BYTES = 10 * 1024 * 1024; // 10MB
const uploadTemplatePdf = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: TEMPLATE_PDF_MAX_BYTES },
  fileFilter: certificatePdfFilter
}).single('template');

const certificateTemplateUploadErrorHandler = (err, req, res, next) => {
  if (res.headersSent) return next(err);
  if (err instanceof multer.MulterError) {
    if (err.code === 'LIMIT_FILE_SIZE') {
      return res.status(400).json({ success: false, message: 'Template file is too large. Maximum size is 10MB.' });
    }
    if (err.code === 'LIMIT_UNEXPECTED_FILE') {
      return res.status(400).json({ success: false, message: 'Unexpected field. Use field name: template.' });
    }
    return res.status(400).json({ success: false, message: err.message || 'File upload error.' });
  }
  if (err.message && err.message.includes('Invalid file type')) {
    return res.status(400).json({ success: false, message: err.message });
  }
  return res.status(400).json({ success: false, message: err.message || 'Certificate template upload failed.' });
};

// All routes require authentication
router.use(auth);

// Get all courses (with filters)
router.get('/', courseController.getCourses);

// Get courses by current instructor (for course management page)
router.get('/my-courses', courseController.getCoursesByInstructor);

// Get current user's progress for all enrolled courses (must be before /:id)
router.get('/my-progress', courseController.getMyProgress);
// Current user's affiliate codes across all courses (must be before /:id)
router.get('/my-affiliate-codes', courseController.getMyAffiliateCodes);

// Save course as draft (can be called from any step)
// IMPORTANT: These routes must come BEFORE /:id routes to avoid route conflicts
router.post('/draft', courseController.saveDraft); // Create new draft
router.post('/:id/draft', courseController.saveDraft); // Update existing draft

// Create new course (draft)
router.post('/', courseController.createCourse);

// Get course by ID (must come after specific routes)
router.get('/:id', courseController.getCourseById);

// Affiliate: list affiliates for course (creator), create code (any user)
router.get('/:id/affiliate', courseController.getAffiliatesByCourse);
router.post('/:id/affiliate', courseController.createAffiliateCode);
// Enrollment and progress (learner flow)
router.post('/:id/enroll', courseController.enroll);
router.post('/:id/checkout', courseController.checkout);
router.get('/:id/progress', courseController.getProgress);
router.post('/:id/progress/complete-lesson', courseController.completeLesson);

// Certificate upload (PDF generated by frontend; multer errors return 400 JSON)
router.post(
  '/:id/certificate/upload',
  (req, res, next) => {
    uploadCertificatePdf(req, res, (err) => {
      if (err) return certificateUploadErrorHandler(err, req, res, next);
      next();
    });
  },
  courseController.uploadCertificate
);

// Certificate template PDF upload (creator saves template for course; stored in S3/local)
router.post(
  '/:id/certificate/template',
  (req, res, next) => {
    uploadTemplatePdf(req, res, (err) => {
      if (err) return certificateTemplateUploadErrorHandler(err, req, res, next);
      next();
    });
  },
  courseController.uploadCertificateTemplate
);

// Update course
router.put('/:id', courseController.updateCourse);

// Publish course
router.post('/:id/publish', courseController.publishCourse);

// Delete course
router.delete('/:id', courseController.deleteCourse);

module.exports = router;

