/**
 * ============================================================================
 * FRONTEND PERMISSIONS CONFIG
 * ============================================================================
 * 
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY!
 * 
 * This file reads from the shared config file:
 *   shared/permissions.config.js
 * 
 * ✅ TO ADD A NEW MODULE:
 *   1. Open: shared/permissions.config.js
 *   2. Add your module to the permissionResources array
 *   3. Add the icon mapping below (if needed)
 *   4. Restart both frontend and backend
 * 
 * ============================================================================
 */

import React from 'react';
import {
  PersonOutline,
  Security as SecurityIcon,
  ArticleOutlined,
  CampaignOutlined,
  StorefrontOutlined,
  StarOutline,
  AnalyticsOutlined,
  DashboardOutlined,
  GroupWorkOutlined,
  VerifiedUserOutlined,
  Notifications as NotificationsIcon,
  InfoOutlined,
  BarChartOutlined,
  BrushOutlined,
  FavoriteBorderOutlined,
  AttachMoneyOutlined,
  SubscriptionsOutlined,
  VolunteerActivismOutlined,
  MenuBook,
  School as SchoolIcon,
} from '@mui/icons-material';

// ✅ Read from shared config (single source of truth)
// Located in frontend/src/shared/ so React can import it
const sharedConfig = require('../shared/permissions.config.js');

export interface PermissionResource {
  name: string;
  IconComponent: React.ElementType;
  path?: string;
  children?: PermissionResource[];
}

// Icon mapping - add new icons here when adding new modules
const iconMap: Record<string, React.ElementType> = {
  'Dashboard': DashboardOutlined,
  'User': PersonOutline,
  'User List': PersonOutline,
  'Invitation': PersonOutline,
  'Creator': StarOutline,
  'Creator Management': StarOutline,
  'Account Management': GroupWorkOutlined,
  'Brand Management': StorefrontOutlined,
  'Roles & Permissions': SecurityIcon,
  'Role Management': SecurityIcon,
  'User Type': GroupWorkOutlined,
  'Notification Control Center': NotificationsIcon,
  'Content': ArticleOutlined,
  'Campaign': CampaignOutlined,
  'Analytics': AnalyticsOutlined,
  'Brand': StorefrontOutlined,
  'Role': SecurityIcon,
  'User Types': GroupWorkOutlined,
  'KYC': VerifiedUserOutlined,
  'Get To Know': InfoOutlined,
  'Learning': SchoolIcon,
  'Courses': MenuBook,
  'Data Board': BarChartOutlined,
  'Canvas Creator': BrushOutlined,
  'Pages': BrushOutlined,
  'Storefront': StorefrontOutlined,
  'Love': FavoriteBorderOutlined,
  'LearnLoop': FavoriteBorderOutlined,
  'VibeLab': FavoriteBorderOutlined,
  'GlowCall': FavoriteBorderOutlined,
  'IRL Meet': FavoriteBorderOutlined,
  'TapIn': FavoriteBorderOutlined,
  'Revenue Desk': AttachMoneyOutlined,
  'Earnings': AttachMoneyOutlined,
  'Transactions': AttachMoneyOutlined,
  'Subscriptions': SubscriptionsOutlined,
  'Withdrawals': AttachMoneyOutlined,
  'PromoBoost': CampaignOutlined,
  'Lead Generation': CampaignOutlined,
  'Broadcasts': CampaignOutlined,
  'Coupons': CampaignOutlined,
  'Unsubscribed Users': CampaignOutlined,
  'Subscription Center': SubscriptionsOutlined,
  'Tiers': SubscriptionsOutlined,
  'TaxDeck': SubscriptionsOutlined,
  'Fan Fund & Donations': VolunteerActivismOutlined,
  // ✅ Add new icon mappings here when adding new modules
  // 'New Module Name': YourIconComponent,
};

// Convert shared config to frontend format with icons
const convertToFrontendFormat = (resources: any[]): PermissionResource[] => {
  return resources.map(resource => ({
    name: resource.name,
    IconComponent: iconMap[resource.name] || InfoOutlined, // Default icon if not found
    path: resource.path,
    children: resource.children?.map((child: any) => ({
      name: child.name,
      IconComponent: iconMap[child.name] || InfoOutlined,
      path: child.path,
    })),
  }));
};

export const permissionResources: PermissionResource[] = convertToFrontendFormat(
  sharedConfig.permissionResources
);

export const allResources = permissionResources.map(r => r.name);
export const permissionActions = ['View', 'Create', 'Edit', 'Delete'] as const;
export type PermissionAction = (typeof permissionActions)[number];
