/**
 * ============================================================================
 * BACKEND PERMISSIONS CONFIG
 * ============================================================================
 * 
 * ⚠️ DO NOT EDIT THIS FILE DIRECTLY!
 * 
 * This file reads from the shared config file:
 *   frontend/src/shared/permissions.config.js
 * 
 * ✅ TO ADD A NEW MODULE:
 *   1. Open: frontend/src/shared/permissions.config.js
 *   2. Add your module to the permissionResources array
 *   3. Restart the backend server
 * 
 * The system will automatically:
 *   - Sync permissions to MongoDB Atlas
 *   - Assign all permissions to Super Admin
 *   - Make them available in Role Management UI
 * 
 * ============================================================================
 */

const path = require('path');

// ✅ Read from shared config file (single source of truth)
// Located in frontend/src/shared/ so both frontend and backend can access it
const sharedConfigPath = path.resolve(__dirname, '../../../frontend/src/shared/permissions.config.js');
const sharedConfig = require(sharedConfigPath);

const permissionResources = sharedConfig.permissionResources;
const permissionActions = sharedConfig.permissionActions;

// Extract all resource names (parent + children)
const allResources = [
  // Parent resources
  ...permissionResources.map(r => r.name),
  // Child resources
  ...permissionResources
    .filter(r => r.children)
    .flatMap(r => r.children.map(child => child.name))
];

module.exports = {
  permissionResources,
  allResources,
  permissionActions
};
